import type { Dataset, Property, Suburb } from './types';
export const suburbs: Suburb[] = [
  {
    id: 'muirhead',
    name: 'Muirhead',
    state: 'NT',
    postcode: '0810',
    median: 748000,
    vacancy: 1.4,
    rentGrowth: 5.8,
    population: 3420,
    x: 2089,
    y: 442,
  },
  {
    id: 'rockingham',
    name: 'Rockingham',
    state: 'WA',
    postcode: '6168',
    median: 654000,
    vacancy: 1.1,
    rentGrowth: 7.2,
    population: 15300,
    x: 566,
    y: 2600,
  },
  {
    id: 'southport',
    name: 'Southport',
    state: 'QLD',
    postcode: '4215',
    median: 790000,
    vacancy: 1.8,
    rentGrowth: 4.5,
    population: 36100,
    x: 4340,
    y: 2270,
  },
  {
    id: 'baldivis',
    name: 'Baldivis',
    state: 'WA',
    postcode: '6171',
    median: 685000,
    vacancy: 1.5,
    rentGrowth: 6.1,
    population: 37900,
    x: 582,
    y: 2616,
  },
  {
    id: 'redbank',
    name: 'Redbank Plains',
    state: 'QLD',
    postcode: '4301',
    median: 670000,
    vacancy: 1.2,
    rentGrowth: 6.8,
    population: 24300,
    x: 4260,
    y: 2170,
  },
  {
    id: 'salisbury',
    name: 'Salisbury',
    state: 'SA',
    postcode: '5108',
    median: 615000,
    vacancy: 1.3,
    rentGrowth: 5.2,
    population: 8970,
    x: 2900,
    y: 2980,
  },
];
const provenance = { source: 'mock', asOf: '2026-09-23', confidence: 'Illustrative' } as const;
export const properties: Property[] = [
  {
    id: 'smith',
    address: '12 Smith St',
    suburbId: 'muirhead',
    price: 720000,
    rent: 720,
    propertyType: 'House',
    beds: 4,
    land: 600,
    score: 87,
    days: 31,
    status: 'For sale',
    why: ['Two price cuts: $760k → $720k (−5.3%)', 'Asking below the illustrative suburb median'],
    questions: ['Insurance quote still needed', 'Rent estimate needs a local appraisal'],
    provenance,
  },
  {
    id: 'jones',
    address: '8 Jones Rd',
    suburbId: 'rockingham',
    price: 680000,
    rent: 720,
    propertyType: 'House',
    beds: 3,
    land: 450,
    score: 84,
    days: 18,
    status: 'For sale',
    why: ['Lowest vacancy in this sample (1.1%)', 'Illustrative rents up 7.2% over 12 months'],
    questions: ['Asking above the suburb median', 'Confirm building condition'],
    provenance,
  },
  {
    id: 'ferry',
    address: '91 Ferry Rd',
    suburbId: 'southport',
    price: 745000,
    rent: 688,
    propertyType: 'House',
    beds: 3,
    land: 520,
    score: 78,
    days: 24,
    status: 'For sale',
    why: ['Price reduced by $15,000', 'Close to established employment centres'],
    questions: ['Parcel-level flood check is outstanding', 'Check ongoing maintenance costs'],
    provenance,
  },
  {
    id: 'lake',
    address: '44 Lake Dr',
    suburbId: 'baldivis',
    price: 705000,
    rent: 715,
    propertyType: 'House',
    beds: 4,
    land: 480,
    score: 81,
    days: 28,
    status: 'Under offer',
    why: ['Four bedrooms and a practical lot size'],
    questions: ['Under offer to another buyer'],
    provenance,
  },
  {
    id: 'wattle',
    address: '27 Wattle Cres',
    suburbId: 'redbank',
    price: 650000,
    rent: 650,
    propertyType: 'House',
    beds: 3,
    land: 610,
    score: 83,
    days: 12,
    status: 'For sale',
    why: ['Inspection candidate', 'Within the default budget'],
    questions: ['Inspect roof and termite history'],
    provenance,
  },
  {
    id: 'park',
    address: '16 Park Ave',
    suburbId: 'salisbury',
    price: 610000,
    rent: 600,
    propertyType: 'House',
    beds: 3,
    land: 560,
    score: 79,
    days: 19,
    status: 'For sale',
    why: ['Accessible entry price in this sample'],
    questions: ['Rental appraisal outstanding'],
    provenance,
  },
  {
    id: 'jacaranda',
    address: '70 Jacaranda Ct',
    suburbId: 'muirhead',
    price: 771000,
    rent: 746,
    propertyType: 'House',
    beds: 4,
    land: 580,
    score: 80,
    days: 1,
    status: 'For sale',
    why: ['New in the sample snapshot'],
    questions: ['Insurance and comparable sales unverified'],
    provenance,
  },
  {
    id: 'grevillea',
    address: '93 Grevillea Way',
    suburbId: 'baldivis',
    price: 700000,
    rent: 683,
    propertyType: 'House',
    beds: 3,
    land: 490,
    score: 82,
    days: 1,
    status: 'For sale',
    why: ['New listing in the sample snapshot'],
    questions: ['Check nearby construction pipeline'],
    provenance,
  },
];
export const dataset: Dataset = {
  properties,
  suburbs,
  events: [
    {
      id: 'e1',
      propertyId: 'smith',
      at: '2026-08-23T00:00:00Z',
      text: 'Listed at $760,000 · sample event',
      kind: 'market',
    },
    {
      id: 'e2',
      propertyId: 'smith',
      at: '2026-09-10T00:00:00Z',
      text: 'Asking price reduced to $740,000 · sample event',
      kind: 'market',
    },
    {
      id: 'e3',
      propertyId: 'smith',
      at: '2026-09-23T00:00:00Z',
      text: 'Asking price reduced to $720,000 · sample event',
      kind: 'market',
    },
    {
      id: 'e4',
      propertyId: 'lake',
      at: '2026-09-23T01:00:00Z',
      text: 'Under offer to another buyer · sample event',
      kind: 'market',
    },
  ],
};
